### ISSUE TITLE
Empty output file from eagle run

### ISSUE THREAD

**Issue by huguanjing** [tony-kuo/eagle#2]
Hi @tony-kuo! 
I followed the `tetraploid_analysis.sh` to prepare vcf and run Star mapping. When it came to the EAGLE step running below script, the run finished but output is empty. Would you please help me to trouble shoot? Thanks a lot!

```
$time eagle -t 8 -a A2-10-R1.refsort.bam -r ../A2Du_13.fasta -v ../A.vs.D.gtf.vcf --splice --rc 1> A2-10-R1.A.vs.D.txt 2> A2-10-R1.A.vs.D.readinfo.txt

real	27m26.761s
user	50m44.891s
sys	1m26.995s

ls -lh
-rw-rw-r--+ 1 hugj2006 domain users    0 Jan 16 17:13 A2-10-R1.A.vs.D.list
-rw-rw-r--+ 1 hugj2006 domain users 817M Jan 16 17:42 A2-10-R1.A.vs.D.readinfo.txt

head A2-10-R1.A.vs.D.readinfo.txt
# Read VCF: ../A.vs.D.gtf.vcf	630309 entries	Fri Jan 17 09:08:17 2020
# Variants within 10 (max window: 0) bp: 503284 entries	Fri Jan 17 09:08:17 2020
# Options: maxh=1024 mvh=1 pao=0 isc=1 nodup=0 splice=1 bs=0 lowmem=1 phred64=0
#          dp=0 gap_op=6 gap_ex=1
#          hetbias=0.5 omega=1e-40 cq=0
#          verbose=1
# Start: 8 threads 	A2-10-R1.refsort.bam	Fri Jan 17 09:08:17 2020
HWI-ST412:220:D0L5UACXX:4:1207:13770:68011	Chr13	123831951	-0.030616	-8.727259	-92.123863	23M84N91M	1		[Chr13,123832117,C,A;]
HWI-ST412:220:D0L5UACXX:4:1207:13770:68011	Chr13	123831951	-0.030616	-9.418283	-92.123863	23M84N91M	1		[Chr13,123832138,T,C;]
HWI-ST412:220:D0L5UACXX:4:1207:13770:68011	Chr13	123831951	-0.030616	-10.569748	-92.123863	23M84N91M	1		[Chr13,123832076,G,A;]
```

**Comment by tony-kuo** [comment]
Hi,

The readinfo.txt file looks fine.  What is the content of A2-10-R1.A.vs.D.txt?

The A2-10-R1.A.vs.D.list file would be generated with the next command, running eagle-rc.
 
In your case it would be:
eagle-rc -a A2-10-R1.refsort.bam -o A2-10-R1.A.vs.D -v A2-10-R1.A.vs.D.txt \
A2-10-R1.A.vs.D.readinfo.txt > A2-10-R1.A.vs.D.list

Did you run this step?

**Comment by huguanjing** [comment]
Thank you for the speedy response! 
I tried both eagle and eagle-rc scripts again and they worked. It turned out my original job was somehow killed halfway so it didn't output 'A2-10-R1.A.vs.D.txt'. Thanks again!
