### ISSUE TITLE
Error running eagle

### ISSUE THREAD

**Issue by signor-molevol** [tony-kuo/eagle#3]
ERROR: (eagle.c:176: errno: None) failed to find 3 in reference

If you have any idea what the issue might be. Error is rather opaque. Reference has the chromosomes it is supposed to, is the right reference. 

./eagle --splice -v variants.vcf -a reads.bam -r reference.fasta > eagletest

**Comment by tony-kuo** [comment]
The error is stating it failed to find "3" in the reference index.  I'm assuming there is a chromosome named >3 in the reference.  Can you show contents of the fasta index file (i.e. reference.fasta.fai)?

**Comment by signor-molevol** [comment]
It is called 3L and 3R. Are letters in chromosome names not supported?
________________________________

**Comment by signor-molevol** [comment]
________________________________

**Comment by tony-kuo** [comment]
Letters in chromosomes are supported.  There is something directly referring to chromosome 3.  Can you check your VCF file to see if there are chromosomes that are not in the reference?

cut -f1 variants.vcf | sort | uniq
will give you a quick peak at chromosomes in your vcf

**Comment by signor-molevol** [comment]
You are absolutely right, the names of the chromosomes were screwed up during the process by the GATK alternate reference maker. Sorry to take your time!

**Comment by tony-kuo** [comment]
No problem. Glad we could figure out the issue.
