### ISSUE TITLE
Compiling error: htslib/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'

### ISSUE THREAD

**Issue by lufuhao** [tony-kuo/eagle#4]
git clone htslib and compiled htslib in eagle root folder
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

$ make
gcc -g -Wall -O2 -pthread -march=native -Lhtslib -Ihtslib -c vector.c util.c calc.c heap.c -lm -lz -llzma -lbz2 -lpthread -lcurl
make -C htslib/
make[1]: Entering directory '/home/lufuhao/P5820T1D2T/Programs/eagle/eagle/htslib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/lufuhao/P5820T1D2T/Programs/eagle/eagle/htslib'
gcc -g -Wall -O2 -pthread -march=native -Lhtslib -Ihtslib eagle.c -o eagle vector.o util.o calc.o heap.o htslib/libhts.a -lm -lz -llzma -lbz2 -lpthread -lcurl
/usr/bin/ld: htslib/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:17: all] Error 1

**Comment by tony-kuo** [comment]
Seems like htslib requires some dependencies you're missing

First try to install libcrypto, in Ubuntu that is:
sudo apt-get install libssl-dev

If that's not enough, after installing the library, try adding to the htslib Makefile
find "htslib_default_libs"
add -lssl -lcrypto

See if that works for you.
